services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./posts_api/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    container_name: posts-nginx
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./posts_api/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    container_name: posts-php
    expose:
      - "9000"
  mysql:
    container_name: posts-mysql
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: postsdb
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASS: "password"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    driver: bridge
